package com.kht.backend.dao;

import com.kht.backend.dataobject.CapAcctDO;

public interface CapAcctDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cap_acct
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int deleteByPrimaryKey(String capCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cap_acct
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int insert(CapAcctDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cap_acct
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int insertSelective(CapAcctDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cap_acct
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    CapAcctDO selectByPrimaryKey(String capCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cap_acct
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int updateByPrimaryKeySelective(CapAcctDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cap_acct
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int updateByPrimaryKey(CapAcctDO record);
}