package com.kht.backend.dao;

import com.kht.backend.dataobject.CapAcctDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface CapAcctDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cap_acct
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    int deleteByPrimaryKey(String capCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cap_acct
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    int insert(CapAcctDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cap_acct
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    int insertSelective(CapAcctDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cap_acct
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    CapAcctDO selectByPrimaryKey(String capCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cap_acct
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    int updateByPrimaryKeySelective(CapAcctDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cap_acct
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    int updateByPrimaryKey(CapAcctDO record);

    List<CapAcctDO> selectByCustomerCode(String customerCode);

    List<CapAcctDO> selectByOrgCode(String orgCode);

    List<CapAcctDO> listAll();

    List<CapAcctDO> selectByOpenTime(@Param("startTime") long startTime, @Param("endTime") long endTime);

    int updatePasswordByPrimaryKey(@Param("capitalCode") String capitalCode, @Param("password") String password);

}