package com.kht.backend.dao;

import com.kht.backend.dataobject.CapAcctDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface CapAcctDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cap_acct
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int deleteByPrimaryKey(String capCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cap_acct
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int insert(CapAcctDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cap_acct
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int insertSelective(CapAcctDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cap_acct
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    CapAcctDO selectByPrimaryKey(String capCode);

    /**
     *
     * @param customerCode
     * @return
     */
    List<CapAcctDO> selectByCustomerCode(String customerCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cap_acct
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int updateByPrimaryKeySelective(CapAcctDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cap_acct
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int updateByPrimaryKey(CapAcctDO record);

    int updatePasswordByPrimaryKey(@Param("capitalCode")String capitalCode,@Param("password") String password);
}