package com.kht.backend.dao;


import com.kht.backend.dataobject.DepAcctDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface DepAcctDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dep_acct
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    int deleteByPrimaryKey(String depCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dep_acct
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    int insert(DepAcctDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dep_acct
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    int insertSelective(DepAcctDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dep_acct
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    DepAcctDO selectByPrimaryKey(String depCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dep_acct
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    int updateByPrimaryKeySelective(DepAcctDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dep_acct
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    int updateByPrimaryKey(DepAcctDO record);

    DepAcctDO selectByCapCode(String capCode);

    List<DepAcctDO> selectByOrgCode(String orgCode);

    List<DepAcctDO> listAll();

    List<DepAcctDO> selectByOpenTime(@Param("startTime") long startTime, @Param("endTime") long endTime);
}