package com.kht.backend.dao;

import com.kht.backend.dataobject.DeptAcctDO;
import org.springframework.stereotype.Repository;

@Repository
public interface DeptAcctDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dep_acct
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int deleteByPrimaryKey(String depCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dep_acct
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int insert(DeptAcctDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dep_acct
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int insertSelective(DeptAcctDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dep_acct
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    DeptAcctDO selectByPrimaryKey(String depCode);

    //TODO
    /**
     *
     * @param customerCode
     * @return
     */
    DeptAcctDO selectByCustomerCode(String customerCode);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dep_acct
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int updateByPrimaryKeySelective(DeptAcctDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dep_acct
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int updateByPrimaryKey(DeptAcctDO record);
}