package com.kht.backend.dao;



import com.kht.backend.dataobject.EmployeeDO;
import org.springframework.stereotype.Component;

import java.util.List;
@Component
public interface EmployeeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    int deleteByPrimaryKey(String employeeCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    int insert(EmployeeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    int insertSelective(EmployeeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    EmployeeDO selectByPrimaryKey(String employeeCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    int updateByPrimaryKeySelective(EmployeeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    int updateByPrimaryKey(EmployeeDO record);

    List<EmployeeDO> selectByName(String name);

    List<EmployeeDO> listAll();
}