package com.kht.backend.dao;

import com.kht.backend.dataobject.MainDateDict;

public interface MainDateDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table main_data_dict
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int deleteByPrimaryKey(Integer mainCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table main_data_dict
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int insert(MainDateDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table main_data_dict
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int insertSelective(MainDateDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table main_data_dict
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    MainDateDict selectByPrimaryKey(Integer mainCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table main_data_dict
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int updateByPrimaryKeySelective(MainDateDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table main_data_dict
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int updateByPrimaryKey(MainDateDict record);
}