package com.kht.backend.dao;

import com.kht.backend.dataobject.OperaLog;

public interface OperaLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opera_log
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int deleteByPrimaryKey(Integer logCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opera_log
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int insert(OperaLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opera_log
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int insertSelective(OperaLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opera_log
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    OperaLog selectByPrimaryKey(Integer logCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opera_log
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int updateByPrimaryKeySelective(OperaLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opera_log
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int updateByPrimaryKey(OperaLog record);
}