package com.kht.backend.dao;

import com.kht.backend.dataobject.OperaLogDO;
import org.springframework.stereotype.Repository;

@Repository
public interface OperaLogDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opera_log
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int deleteByPrimaryKey(Integer logCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opera_log
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int insert(OperaLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opera_log
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int insertSelective(OperaLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opera_log
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    OperaLogDO selectByPrimaryKey(Integer logCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opera_log
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int updateByPrimaryKeySelective(OperaLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opera_log
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int updateByPrimaryKey(OperaLogDO record);
}