package com.kht.backend.dao;

import com.kht.backend.dataobject.OperationDO;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Repository;

import java.util.List;

@Component
public interface OperationDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated Thu Jun 20 16:40:33 CST 2019
     */
    int deleteByPrimaryKey(Integer operaCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated Thu Jun 20 16:40:33 CST 2019
     */
    int insert(OperationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated Thu Jun 20 16:40:33 CST 2019
     */
    int insertSelective(OperationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated Thu Jun 20 16:40:33 CST 2019
     */
    OperationDO selectByPrimaryKey(Integer operaCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated Thu Jun 20 16:40:33 CST 2019
     */
    int updateByPrimaryKeySelective(OperationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated Thu Jun 20 16:40:33 CST 2019
     */
    int updateByPrimaryKey(OperationDO record);

    List<OperationDO> listAll();
    List<OperationDO> selectByPosition(int posCode);
}