package com.kht.backend.dao;

import com.kht.backend.dataobject.PosOperaRelDO;

public interface PosOperaRelDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pos_opera_rel
     *
     * @mbg.generated Thu Jun 20 16:40:33 CST 2019
     */
    int deleteByPrimaryKey(Integer relCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pos_opera_rel
     *
     * @mbg.generated Thu Jun 20 16:40:33 CST 2019
     */
    int insert(PosOperaRelDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pos_opera_rel
     *
     * @mbg.generated Thu Jun 20 16:40:33 CST 2019
     */
    int insertSelective(PosOperaRelDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pos_opera_rel
     *
     * @mbg.generated Thu Jun 20 16:40:33 CST 2019
     */
    PosOperaRelDO selectByPrimaryKey(Integer relCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pos_opera_rel
     *
     * @mbg.generated Thu Jun 20 16:40:33 CST 2019
     */
    int updateByPrimaryKeySelective(PosOperaRelDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pos_opera_rel
     *
     * @mbg.generated Thu Jun 20 16:40:33 CST 2019
     */
    int updateByPrimaryKey(PosOperaRelDO record);
}