package com.kht.backend.dao;


import com.kht.backend.dataobject.SysParaDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface SysParaDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_para
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    int deleteByPrimaryKey(Integer paraCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_para
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    int insert(SysParaDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_para
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    int insertSelective(SysParaDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_para
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    SysParaDO selectByPrimaryKey(Integer paraCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_para
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    int updateByPrimaryKeySelective(SysParaDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_para
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    int updateByPrimaryKey(SysParaDO record);

    int updateParaValueByPrimaryKeySelective(@Param("paraCode") int paraCode,@Param("paraValue") String paraValue);

    List<SysParaDO> listAll();

    SysParaDO selectByParaName(String paraName);
}