package com.kht.backend.dao;

import com.kht.backend.dataobject.SysparaDO;
import org.springframework.stereotype.Repository;

@Repository
public interface SysparaDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_para
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int deleteByPrimaryKey(Integer paraCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_para
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int insert(SysparaDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_para
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int insertSelective(SysparaDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_para
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    SysparaDO selectByPrimaryKey(Integer paraCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_para
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int updateByPrimaryKeySelective(SysparaDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_para
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    int updateByPrimaryKey(SysparaDO record);
}