package com.kht.backend.dao;


import com.kht.backend.dataobject.SysparaDO;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface SysparaDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_para
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    int deleteByPrimaryKey(Integer paraCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_para
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    int insert(SysparaDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_para
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    int insertSelective(SysparaDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_para
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    SysparaDO selectByPrimaryKey(Integer paraCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_para
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    int updateByPrimaryKeySelective(SysparaDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_para
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    int updateByPrimaryKey(SysparaDO record);

    int updateParaValueByPrimaryKeySelective(int paraCode,String paraValue);

    List<SysparaDO> listAll();
}