package com.kht.backend.dataobject;

public class AcctOpenInfoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.INFO_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private Integer infoCode;

    private Integer userCode;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.USER_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private Integer userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.IMG_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private Integer imgCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.NAME
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.GENDER
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.ID_TYPE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String idType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.ID_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String idCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.ID_EFF_DATE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private Long idEffDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.ID_EXP_DATE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private Long idExpDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.TELEPHONE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private Long telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.EMAIL
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.ADDRESS
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.OCCUPATION
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String occupation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.COMPANY
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.EDUCATION
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.ORG_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String orgCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.ANS_ONE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String ansOne;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.ANS_TWO
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String ansTwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.ANS_THREE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String ansThree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.ANS_FOUR
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String ansFour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.ANS_FIVE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String ansFive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.ANS_SIX
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String ansSix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.ANS_SEVEN
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String ansSeven;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.ANS_EIGHT
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String ansEight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.ANS_NINE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String ansNine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.ANS_TEN
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String ansTen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.BANK_TYPE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String bankType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.BANK_CARD_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String bankCardCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.OPEN_CHANNEL
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String openChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.CMT_TIME
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private Long cmtTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_open_info.INFO_STATUS
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String infoStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.INFO_CODE
     *
     * @return the value of acct_open_info.INFO_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public Integer getInfoCode() {
        return infoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.INFO_CODE
     *
     * @param infoCode the value for acct_open_info.INFO_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setInfoCode(Integer infoCode) {
        this.infoCode = infoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.USER_CODE
     *
     * @return the value of acct_open_info.USER_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public Integer getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.USER_CODE
     *
     * @param userCode the value for acct_open_info.USER_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setUserCode(Integer userCode) {
        this.userCode = userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.IMG_CODE
     *
     * @return the value of acct_open_info.IMG_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public Integer getImgCode() {
        return imgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.IMG_CODE
     *
     * @param imgCode the value for acct_open_info.IMG_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setImgCode(Integer imgCode) {
        this.imgCode = imgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.NAME
     *
     * @return the value of acct_open_info.NAME
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.NAME
     *
     * @param name the value for acct_open_info.NAME
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.GENDER
     *
     * @return the value of acct_open_info.GENDER
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.GENDER
     *
     * @param gender the value for acct_open_info.GENDER
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.ID_TYPE
     *
     * @return the value of acct_open_info.ID_TYPE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getIdType() {
        return idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.ID_TYPE
     *
     * @param idType the value for acct_open_info.ID_TYPE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setIdType(String idType) {
        this.idType = idType == null ? null : idType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.ID_CODE
     *
     * @return the value of acct_open_info.ID_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getIdCode() {
        return idCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.ID_CODE
     *
     * @param idCode the value for acct_open_info.ID_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setIdCode(String idCode) {
        this.idCode = idCode == null ? null : idCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.ID_EFF_DATE
     *
     * @return the value of acct_open_info.ID_EFF_DATE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public Long getIdEffDate() {
        return idEffDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.ID_EFF_DATE
     *
     * @param idEffDate the value for acct_open_info.ID_EFF_DATE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setIdEffDate(Long idEffDate) {
        this.idEffDate = idEffDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.ID_EXP_DATE
     *
     * @return the value of acct_open_info.ID_EXP_DATE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public Long getIdExpDate() {
        return idExpDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.ID_EXP_DATE
     *
     * @param idExpDate the value for acct_open_info.ID_EXP_DATE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setIdExpDate(Long idExpDate) {
        this.idExpDate = idExpDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.TELEPHONE
     *
     * @return the value of acct_open_info.TELEPHONE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public Long getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.TELEPHONE
     *
     * @param telephone the value for acct_open_info.TELEPHONE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setTelephone(Long telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.EMAIL
     *
     * @return the value of acct_open_info.EMAIL
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.EMAIL
     *
     * @param email the value for acct_open_info.EMAIL
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.ADDRESS
     *
     * @return the value of acct_open_info.ADDRESS
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.ADDRESS
     *
     * @param address the value for acct_open_info.ADDRESS
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.OCCUPATION
     *
     * @return the value of acct_open_info.OCCUPATION
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getOccupation() {
        return occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.OCCUPATION
     *
     * @param occupation the value for acct_open_info.OCCUPATION
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setOccupation(String occupation) {
        this.occupation = occupation == null ? null : occupation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.COMPANY
     *
     * @return the value of acct_open_info.COMPANY
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.COMPANY
     *
     * @param company the value for acct_open_info.COMPANY
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.EDUCATION
     *
     * @return the value of acct_open_info.EDUCATION
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.EDUCATION
     *
     * @param education the value for acct_open_info.EDUCATION
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.ORG_CODE
     *
     * @return the value of acct_open_info.ORG_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.ORG_CODE
     *
     * @param orgCode the value for acct_open_info.ORG_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.ANS_ONE
     *
     * @return the value of acct_open_info.ANS_ONE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getAnsOne() {
        return ansOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.ANS_ONE
     *
     * @param ansOne the value for acct_open_info.ANS_ONE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setAnsOne(String ansOne) {
        this.ansOne = ansOne == null ? null : ansOne.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.ANS_TWO
     *
     * @return the value of acct_open_info.ANS_TWO
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getAnsTwo() {
        return ansTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.ANS_TWO
     *
     * @param ansTwo the value for acct_open_info.ANS_TWO
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setAnsTwo(String ansTwo) {
        this.ansTwo = ansTwo == null ? null : ansTwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.ANS_THREE
     *
     * @return the value of acct_open_info.ANS_THREE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getAnsThree() {
        return ansThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.ANS_THREE
     *
     * @param ansThree the value for acct_open_info.ANS_THREE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setAnsThree(String ansThree) {
        this.ansThree = ansThree == null ? null : ansThree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.ANS_FOUR
     *
     * @return the value of acct_open_info.ANS_FOUR
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getAnsFour() {
        return ansFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.ANS_FOUR
     *
     * @param ansFour the value for acct_open_info.ANS_FOUR
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setAnsFour(String ansFour) {
        this.ansFour = ansFour == null ? null : ansFour.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.ANS_FIVE
     *
     * @return the value of acct_open_info.ANS_FIVE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getAnsFive() {
        return ansFive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.ANS_FIVE
     *
     * @param ansFive the value for acct_open_info.ANS_FIVE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setAnsFive(String ansFive) {
        this.ansFive = ansFive == null ? null : ansFive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.ANS_SIX
     *
     * @return the value of acct_open_info.ANS_SIX
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getAnsSix() {
        return ansSix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.ANS_SIX
     *
     * @param ansSix the value for acct_open_info.ANS_SIX
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setAnsSix(String ansSix) {
        this.ansSix = ansSix == null ? null : ansSix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.ANS_SEVEN
     *
     * @return the value of acct_open_info.ANS_SEVEN
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getAnsSeven() {
        return ansSeven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.ANS_SEVEN
     *
     * @param ansSeven the value for acct_open_info.ANS_SEVEN
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setAnsSeven(String ansSeven) {
        this.ansSeven = ansSeven == null ? null : ansSeven.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.ANS_EIGHT
     *
     * @return the value of acct_open_info.ANS_EIGHT
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getAnsEight() {
        return ansEight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.ANS_EIGHT
     *
     * @param ansEight the value for acct_open_info.ANS_EIGHT
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setAnsEight(String ansEight) {
        this.ansEight = ansEight == null ? null : ansEight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.ANS_NINE
     *
     * @return the value of acct_open_info.ANS_NINE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getAnsNine() {
        return ansNine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.ANS_NINE
     *
     * @param ansNine the value for acct_open_info.ANS_NINE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setAnsNine(String ansNine) {
        this.ansNine = ansNine == null ? null : ansNine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.ANS_TEN
     *
     * @return the value of acct_open_info.ANS_TEN
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getAnsTen() {
        return ansTen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.ANS_TEN
     *
     * @param ansTen the value for acct_open_info.ANS_TEN
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setAnsTen(String ansTen) {
        this.ansTen = ansTen == null ? null : ansTen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.BANK_TYPE
     *
     * @return the value of acct_open_info.BANK_TYPE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getBankType() {
        return bankType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.BANK_TYPE
     *
     * @param bankType the value for acct_open_info.BANK_TYPE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setBankType(String bankType) {
        this.bankType = bankType == null ? null : bankType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.BANK_CARD_CODE
     *
     * @return the value of acct_open_info.BANK_CARD_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getBankCardCode() {
        return bankCardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.BANK_CARD_CODE
     *
     * @param bankCardCode the value for acct_open_info.BANK_CARD_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setBankCardCode(String bankCardCode) {
        this.bankCardCode = bankCardCode == null ? null : bankCardCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.OPEN_CHANNEL
     *
     * @return the value of acct_open_info.OPEN_CHANNEL
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getOpenChannel() {
        return openChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.OPEN_CHANNEL
     *
     * @param openChannel the value for acct_open_info.OPEN_CHANNEL
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setOpenChannel(String openChannel) {
        this.openChannel = openChannel == null ? null : openChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.CMT_TIME
     *
     * @return the value of acct_open_info.CMT_TIME
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public Long getCmtTime() {
        return cmtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.CMT_TIME
     *
     * @param cmtTime the value for acct_open_info.CMT_TIME
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setCmtTime(Long cmtTime) {
        this.cmtTime = cmtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_open_info.INFO_STATUS
     *
     * @return the value of acct_open_info.INFO_STATUS
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getInfoStatus() {
        return infoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_open_info.INFO_STATUS
     *
     * @param infoStatus the value for acct_open_info.INFO_STATUS
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setInfoStatus(String infoStatus) {
        this.infoStatus = infoStatus == null ? null : infoStatus.trim();
    }
}