package com.kht.backend.dataobject;

public class CapAcctDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cap_acct.CAP_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private String capCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cap_acct.CUST_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private String custCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cap_acct.DEP_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private String depCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cap_acct.CAP_PWD
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private String capPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cap_acct.CURRENCY
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private String currency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cap_acct.MAIN_FLAG
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private Boolean mainFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cap_acct.ATTR
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private String attr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cap_acct.ORG_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private Integer orgCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cap_acct.OPEN_TIME
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private Long openTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cap_acct.CLOSE_TIME
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private Long closeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cap_acct.CAP_STATUS
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private String capStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cap_acct.CAP_CODE
     *
     * @return the value of cap_acct.CAP_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public String getCapCode() {
        return capCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cap_acct.CAP_CODE
     *
     * @param capCode the value for cap_acct.CAP_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setCapCode(String capCode) {
        this.capCode = capCode == null ? null : capCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cap_acct.CUST_CODE
     *
     * @return the value of cap_acct.CUST_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public String getCustCode() {
        return custCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cap_acct.CUST_CODE
     *
     * @param custCode the value for cap_acct.CUST_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setCustCode(String custCode) {
        this.custCode = custCode == null ? null : custCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cap_acct.DEP_CODE
     *
     * @return the value of cap_acct.DEP_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public String getDepCode() {
        return depCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cap_acct.DEP_CODE
     *
     * @param depCode the value for cap_acct.DEP_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setDepCode(String depCode) {
        this.depCode = depCode == null ? null : depCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cap_acct.CAP_PWD
     *
     * @return the value of cap_acct.CAP_PWD
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public String getCapPwd() {
        return capPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cap_acct.CAP_PWD
     *
     * @param capPwd the value for cap_acct.CAP_PWD
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setCapPwd(String capPwd) {
        this.capPwd = capPwd == null ? null : capPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cap_acct.CURRENCY
     *
     * @return the value of cap_acct.CURRENCY
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cap_acct.CURRENCY
     *
     * @param currency the value for cap_acct.CURRENCY
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cap_acct.MAIN_FLAG
     *
     * @return the value of cap_acct.MAIN_FLAG
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public Boolean getMainFlag() {
        return mainFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cap_acct.MAIN_FLAG
     *
     * @param mainFlag the value for cap_acct.MAIN_FLAG
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setMainFlag(Boolean mainFlag) {
        this.mainFlag = mainFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cap_acct.ATTR
     *
     * @return the value of cap_acct.ATTR
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public String getAttr() {
        return attr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cap_acct.ATTR
     *
     * @param attr the value for cap_acct.ATTR
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setAttr(String attr) {
        this.attr = attr == null ? null : attr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cap_acct.ORG_CODE
     *
     * @return the value of cap_acct.ORG_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public Integer getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cap_acct.ORG_CODE
     *
     * @param orgCode the value for cap_acct.ORG_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setOrgCode(Integer orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cap_acct.OPEN_TIME
     *
     * @return the value of cap_acct.OPEN_TIME
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public Long getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cap_acct.OPEN_TIME
     *
     * @param openTime the value for cap_acct.OPEN_TIME
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setOpenTime(Long openTime) {
        this.openTime = openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cap_acct.CLOSE_TIME
     *
     * @return the value of cap_acct.CLOSE_TIME
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public Long getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cap_acct.CLOSE_TIME
     *
     * @param closeTime the value for cap_acct.CLOSE_TIME
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setCloseTime(Long closeTime) {
        this.closeTime = closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cap_acct.CAP_STATUS
     *
     * @return the value of cap_acct.CAP_STATUS
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public String getCapStatus() {
        return capStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cap_acct.CAP_STATUS
     *
     * @param capStatus the value for cap_acct.CAP_STATUS
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setCapStatus(String capStatus) {
        this.capStatus = capStatus == null ? null : capStatus.trim();
    }
}