package com.kht.backend.dataobject;

public class EmployeeDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.EMPLOYEE_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private String employeeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.EMPLOYEE_PWD
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private String employeePwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.EMPLOYEE_NAME
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private String employeeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.ID_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private String idCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.TELEPHONE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private Long telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.EMAIL
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.ADDRESS
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.POS_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private Integer posCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.EMPLOYEE_STATUS
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private String employeeStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.EMPLOYEE_CODE
     *
     * @return the value of employee.EMPLOYEE_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public String getEmployeeCode() {
        return employeeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.EMPLOYEE_CODE
     *
     * @param employeeCode the value for employee.EMPLOYEE_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode == null ? null : employeeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.EMPLOYEE_PWD
     *
     * @return the value of employee.EMPLOYEE_PWD
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public String getEmployeePwd() {
        return employeePwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.EMPLOYEE_PWD
     *
     * @param employeePwd the value for employee.EMPLOYEE_PWD
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setEmployeePwd(String employeePwd) {
        this.employeePwd = employeePwd == null ? null : employeePwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.EMPLOYEE_NAME
     *
     * @return the value of employee.EMPLOYEE_NAME
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.EMPLOYEE_NAME
     *
     * @param employeeName the value for employee.EMPLOYEE_NAME
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName == null ? null : employeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.ID_CODE
     *
     * @return the value of employee.ID_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public String getIdCode() {
        return idCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.ID_CODE
     *
     * @param idCode the value for employee.ID_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setIdCode(String idCode) {
        this.idCode = idCode == null ? null : idCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.TELEPHONE
     *
     * @return the value of employee.TELEPHONE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public Long getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.TELEPHONE
     *
     * @param telephone the value for employee.TELEPHONE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setTelephone(Long telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.EMAIL
     *
     * @return the value of employee.EMAIL
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.EMAIL
     *
     * @param email the value for employee.EMAIL
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.ADDRESS
     *
     * @return the value of employee.ADDRESS
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.ADDRESS
     *
     * @param address the value for employee.ADDRESS
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.POS_CODE
     *
     * @return the value of employee.POS_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public Integer getPosCode() {
        return posCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.POS_CODE
     *
     * @param posCode the value for employee.POS_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setPosCode(Integer posCode) {
        this.posCode = posCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.EMPLOYEE_STATUS
     *
     * @return the value of employee.EMPLOYEE_STATUS
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public String getEmployeeStatus() {
        return employeeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.EMPLOYEE_STATUS
     *
     * @param employeeStatus the value for employee.EMPLOYEE_STATUS
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setEmployeeStatus(String employeeStatus) {
        this.employeeStatus = employeeStatus == null ? null : employeeStatus.trim();
    }
}