package com.kht.backend.dataobject;

import java.io.Serializable;

public class OperationDO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.OPERA_CODE
     *
     * @mbg.generated Thu Jun 20 16:40:33 CST 2019
     */
    private Integer operaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.OPERA_NAME
     *
     * @mbg.generated Thu Jun 20 16:40:33 CST 2019
     */
    private String operaName;

    private String url;

    private String operaType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.OPERA_CODE
     *
     * @return the value of operation.OPERA_CODE
     *
     * @mbg.generated Thu Jun 20 16:40:33 CST 2019
     */
    public Integer getOperaCode() {
        return operaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.OPERA_CODE
     *
     * @param operaCode the value for operation.OPERA_CODE
     *
     * @mbg.generated Thu Jun 20 16:40:33 CST 2019
     */
    public void setOperaCode(Integer operaCode) {
        this.operaCode = operaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.OPERA_NAME
     *
     * @return the value of operation.OPERA_NAME
     *
     * @mbg.generated Thu Jun 20 16:40:33 CST 2019
     */
    public String getOperaName() {
        return operaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.OPERA_NAME
     *
     * @param operaName the value for operation.OPERA_NAME
     *
     * @mbg.generated Thu Jun 20 16:40:33 CST 2019
     */
    public void setOperaName(String operaName) {
        this.operaName = operaName == null ? null : operaName.trim();
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    public String getOperaType() {
        return operaType;
    }

    public void setOperaType(String operaType) {
        this.operaType = operaType == null ? null : operaType.trim();
    }
}