package com.kht.backend.dataobject;

import org.springframework.stereotype.Component;

public class OrganizationDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.ORG_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private String orgCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.ORG_NAME
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private String orgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.ORG_ADDR
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private String orgAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.ORG_TEL
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private Long orgTel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.ORG_CODE
     *
     * @return the value of organization.ORG_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.ORG_CODE
     *
     * @param orgCode the value for organization.ORG_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.ORG_NAME
     *
     * @return the value of organization.ORG_NAME
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.ORG_NAME
     *
     * @param orgName the value for organization.ORG_NAME
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.ORG_ADDR
     *
     * @return the value of organization.ORG_ADDR
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public String getOrgAddr() {
        return orgAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.ORG_ADDR
     *
     * @param orgAddr the value for organization.ORG_ADDR
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setOrgAddr(String orgAddr) {
        this.orgAddr = orgAddr == null ? null : orgAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.ORG_TEL
     *
     * @return the value of organization.ORG_TEL
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public Long getOrgTel() {
        return orgTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.ORG_TEL
     *
     * @param orgTel the value for organization.ORG_TEL
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setOrgTel(Long orgTel) {
        this.orgTel = orgTel;
    }
}