package com.kht.backend.dataobject;

public class PositionDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.POS_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private Integer posCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.POSITION
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String posName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.OPERATION
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public Integer getPosCode() {
        return posCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.POS_CODE
     *
     * @param posCode the value for position.POS_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setPosCode(Integer posCode) {
        this.posCode = posCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.POSITION
     *
     * @return the value of position.POS_NAME
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getPosName() {
        return posName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.POSITION
     *
     * @param posName the value for position.POS_NAME
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setPosName(String posName) {
        this.posName = posName == null ? null : posName.trim();
    }

}