package com.kht.backend.dataobject;

public class PositionDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.POS_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private Integer posCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.POSITION
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.OPERATION
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String operation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.POS_CODE
     *
     * @return the value of position.POS_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public Integer getPosCode() {
        return posCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.POS_CODE
     *
     * @param posCode the value for position.POS_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setPosCode(Integer posCode) {
        this.posCode = posCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.POSITION
     *
     * @return the value of position.POSITION
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.POSITION
     *
     * @param position the value for position.POSITION
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.OPERATION
     *
     * @return the value of position.OPERATION
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.OPERATION
     *
     * @param operation the value for position.OPERATION
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setOperation(String operation) {
        this.operation = operation == null ? null : operation.trim();
    }
}