package com.kht.backend.dataobject;

public class PosOperaRelDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_opera_rel.REL_CODE
     *
     * @mbg.generated Thu Jun 20 16:40:33 CST 2019
     */
    private Integer relCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_opera_rel.POS_CODE
     *
     * @mbg.generated Thu Jun 20 16:40:33 CST 2019
     */
    private Integer posCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_opera_rel.OPERA_CODE
     *
     * @mbg.generated Thu Jun 20 16:40:33 CST 2019
     */
    private Integer operaCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_opera_rel.REL_CODE
     *
     * @return the value of pos_opera_rel.REL_CODE
     *
     * @mbg.generated Thu Jun 20 16:40:33 CST 2019
     */
    public Integer getRelCode() {
        return relCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_opera_rel.REL_CODE
     *
     * @param relCode the value for pos_opera_rel.REL_CODE
     *
     * @mbg.generated Thu Jun 20 16:40:33 CST 2019
     */
    public void setRelCode(Integer relCode) {
        this.relCode = relCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_opera_rel.POS_CODE
     *
     * @return the value of pos_opera_rel.POS_CODE
     *
     * @mbg.generated Thu Jun 20 16:40:33 CST 2019
     */
    public Integer getPosCode() {
        return posCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_opera_rel.POS_CODE
     *
     * @param posCode the value for pos_opera_rel.POS_CODE
     *
     * @mbg.generated Thu Jun 20 16:40:33 CST 2019
     */
    public void setPosCode(Integer posCode) {
        this.posCode = posCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_opera_rel.OPERA_CODE
     *
     * @return the value of pos_opera_rel.OPERA_CODE
     *
     * @mbg.generated Thu Jun 20 16:40:33 CST 2019
     */
    public Integer getOperaCode() {
        return operaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_opera_rel.OPERA_CODE
     *
     * @param operaCode the value for pos_opera_rel.OPERA_CODE
     *
     * @mbg.generated Thu Jun 20 16:40:33 CST 2019
     */
    public void setOperaCode(Integer operaCode) {
        this.operaCode = operaCode;
    }
}