package com.kht.backend.dataobject;

public class SubDataDictDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_data_dict.SUB_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private Integer subCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_data_dict.MAIN_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private Integer mainCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_data_dict.VALUE_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String valueCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_data_dict.VALUE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_data_dict.SUB_CODE
     *
     * @return the value of sub_data_dict.SUB_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public Integer getSubCode() {
        return subCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_data_dict.SUB_CODE
     *
     * @param subCode the value for sub_data_dict.SUB_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setSubCode(Integer subCode) {
        this.subCode = subCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_data_dict.MAIN_CODE
     *
     * @return the value of sub_data_dict.MAIN_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public Integer getMainCode() {
        return mainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_data_dict.MAIN_CODE
     *
     * @param mainCode the value for sub_data_dict.MAIN_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setMainCode(Integer mainCode) {
        this.mainCode = mainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_data_dict.VALUE_CODE
     *
     * @return the value of sub_data_dict.VALUE_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getValueCode() {
        return valueCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_data_dict.VALUE_CODE
     *
     * @param valueCode the value for sub_data_dict.VALUE_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setValueCode(String valueCode) {
        this.valueCode = valueCode == null ? null : valueCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_data_dict.VALUE
     *
     * @return the value of sub_data_dict.VALUE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_data_dict.VALUE
     *
     * @param value the value for sub_data_dict.VALUE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}