package com.kht.backend.dataobject;

public class SysparaDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_para.PARA_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private Integer paraCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_para.PARA_NAME
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private String paraName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_para.PARA_VALUE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private String paraValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_para.PARA_CODE
     *
     * @return the value of sys_para.PARA_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public Integer getParaCode() {
        return paraCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_para.PARA_CODE
     *
     * @param paraCode the value for sys_para.PARA_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setParaCode(Integer paraCode) {
        this.paraCode = paraCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_para.PARA_NAME
     *
     * @return the value of sys_para.PARA_NAME
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public String getParaName() {
        return paraName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_para.PARA_NAME
     *
     * @param paraName the value for sys_para.PARA_NAME
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setParaName(String paraName) {
        this.paraName = paraName == null ? null : paraName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_para.PARA_VALUE
     *
     * @return the value of sys_para.PARA_VALUE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public String getParaValue() {
        return paraValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_para.PARA_VALUE
     *
     * @param paraValue the value for sys_para.PARA_VALUE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setParaValue(String paraValue) {
        this.paraValue = paraValue == null ? null : paraValue.trim();
    }
}