package com.kht.backend.dataobject;

public class TrdAcctDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trd_acct.TRD_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String trdCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trd_acct.CUST_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String custCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trd_acct.STK_EX
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String stkEx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trd_acct.STK_BD
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String stkBd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trd_acct.CUST_TYPE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String custType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trd_acct.TRD_UNIT
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String trdUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trd_acct.OPEN_TIME
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private Long openTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trd_acct.CLOSE_TIME
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private Long closeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trd_acct.TDR_STATUS
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    private String tdrStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trd_acct.TRD_CODE
     *
     * @return the value of trd_acct.TRD_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getTrdCode() {
        return trdCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trd_acct.TRD_CODE
     *
     * @param trdCode the value for trd_acct.TRD_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setTrdCode(String trdCode) {
        this.trdCode = trdCode == null ? null : trdCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trd_acct.CUST_CODE
     *
     * @return the value of trd_acct.CUST_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getCustCode() {
        return custCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trd_acct.CUST_CODE
     *
     * @param custCode the value for trd_acct.CUST_CODE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setCustCode(String custCode) {
        this.custCode = custCode == null ? null : custCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trd_acct.STK_EX
     *
     * @return the value of trd_acct.STK_EX
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getStkEx() {
        return stkEx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trd_acct.STK_EX
     *
     * @param stkEx the value for trd_acct.STK_EX
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setStkEx(String stkEx) {
        this.stkEx = stkEx == null ? null : stkEx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trd_acct.STK_BD
     *
     * @return the value of trd_acct.STK_BD
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getStkBd() {
        return stkBd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trd_acct.STK_BD
     *
     * @param stkBd the value for trd_acct.STK_BD
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setStkBd(String stkBd) {
        this.stkBd = stkBd == null ? null : stkBd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trd_acct.CUST_TYPE
     *
     * @return the value of trd_acct.CUST_TYPE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getCustType() {
        return custType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trd_acct.CUST_TYPE
     *
     * @param custType the value for trd_acct.CUST_TYPE
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setCustType(String custType) {
        this.custType = custType == null ? null : custType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trd_acct.TRD_UNIT
     *
     * @return the value of trd_acct.TRD_UNIT
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getTrdUnit() {
        return trdUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trd_acct.TRD_UNIT
     *
     * @param trdUnit the value for trd_acct.TRD_UNIT
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setTrdUnit(String trdUnit) {
        this.trdUnit = trdUnit == null ? null : trdUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trd_acct.OPEN_TIME
     *
     * @return the value of trd_acct.OPEN_TIME
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public Long getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trd_acct.OPEN_TIME
     *
     * @param openTime the value for trd_acct.OPEN_TIME
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setOpenTime(Long openTime) {
        this.openTime = openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trd_acct.CLOSE_TIME
     *
     * @return the value of trd_acct.CLOSE_TIME
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public Long getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trd_acct.CLOSE_TIME
     *
     * @param closeTime the value for trd_acct.CLOSE_TIME
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setCloseTime(Long closeTime) {
        this.closeTime = closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trd_acct.TDR_STATUS
     *
     * @return the value of trd_acct.TDR_STATUS
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public String getTdrStatus() {
        return tdrStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trd_acct.TDR_STATUS
     *
     * @param tdrStatus the value for trd_acct.TDR_STATUS
     *
     * @mbg.generated Wed Jun 19 15:57:39 CST 2019
     */
    public void setTdrStatus(String tdrStatus) {
        this.tdrStatus = tdrStatus == null ? null : tdrStatus.trim();
    }
}