package com.kht.backend.dataobject;

public class UserDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private Integer userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.TELEPHONE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private Long telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.INFO_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private Integer infoCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.CUST_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private String custCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.PASSWORD
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_CODE
     *
     * @return the value of user.USER_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public Integer getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_CODE
     *
     * @param userCode the value for user.USER_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setUserCode(Integer userCode) {
        this.userCode = userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.TELEPHONE
     *
     * @return the value of user.TELEPHONE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public Long getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.TELEPHONE
     *
     * @param telephone the value for user.TELEPHONE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setTelephone(Long telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.INFO_CODE
     *
     * @return the value of user.INFO_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public Integer getInfoCode() {
        return infoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.INFO_CODE
     *
     * @param infoCode the value for user.INFO_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setInfoCode(Integer infoCode) {
        this.infoCode = infoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.CUST_CODE
     *
     * @return the value of user.CUST_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public String getCustCode() {
        return custCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.CUST_CODE
     *
     * @param custCode the value for user.CUST_CODE
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setCustCode(String custCode) {
        this.custCode = custCode == null ? null : custCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.PASSWORD
     *
     * @return the value of user.PASSWORD
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.PASSWORD
     *
     * @param password the value for user.PASSWORD
     *
     * @mbg.generated Sun Jun 16 10:25:53 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}